openapi: 3.0.1
info:
  title: Keksipurkki Pet Clinic
  description: |2+

    Sample implementation of a REST API demonstrating
    the lessons learned over the years on microservice
    development.

    Powered by Eclipse Vert.x — https://vertx.io

  version: 1.0.0
servers:
- url: http://localhost:8080/petclinic/v1
  variables: {}
